# Generated by Django 5.2.16 on 2026-07-28 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0006_alter_job_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.CharField(max_length=255)),
                ('match_score', models.FloatField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'ordering': ['-match_score'],
                'unique_together': {('supabase_uid', 'job')},
            },
        ),
    ]
