# Generated by Django 5.2.16 on 2026-07-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('job_type', models.CharField(blank=True, choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('freelance', 'Freelance'), ('remote', 'Remote'), ('internship', 'Internship')], default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('source', models.CharField(blank=True, choices=[('greenhouse', 'Greenhouse'), ('ashby', 'Ashby'), ('remoteok', 'RemoteOK'), ('arbeitnow', 'Arbeitnow'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('rozee', 'Rozee'), ('wellfound', 'Wellfound')], default='', max_length=20)),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('source_id', models.CharField(blank=True, default='', max_length=500)),
                ('is_remote', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('date_fetched', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-date_posted'],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
