# Generated by Django 5.2.16 on 2026-07-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('remote', 'Remote'), ('internship', 'Internship')], max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('ashby', 'Ashby'), ('remoteok', 'RemoteOK'), ('arbeitnow', 'ArbeitNow'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('rozee', 'Rozee'), ('wellfound', 'Wellfound')], max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='source_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source'], name='jobs_job_source_e2155e_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['country'], name='jobs_job_country_45de34_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['job_type'], name='jobs_job_job_typ_f6c220_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_remote'], name='jobs_job_is_remo_78fc35_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['date_posted'], name='jobs_job_date_po_dc50ec_idx'),
        ),
        migrations.AlterModelTable(
            name='job',
            table=None,
        ),
    ]
