# Generated by Django 5.2.16 on 2026-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company_alter_job_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
