# Generated by Django 5.2.16 on 2026-07-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('ashby', 'Ashby'), ('remoteok', 'RemoteOK'), ('arbeitnow', 'ArbeitNow'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('rozee', 'Rozee'), ('wellfound', 'Wellfound'), ('ycombinator', 'Y Combinator')], max_length=30),
        ),
    ]
