# Generated by Django 5.2.16 on 2026-07-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('greenhouse', 'Greenhouse'), ('ashby', 'Ashby'), ('remoteok', 'RemoteOK'), ('arbeitnow', 'ArbeitNow'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('glassdoor', 'Glassdoor'), ('rozee', 'Rozee'), ('wellfound', 'Wellfound'), ('ycombinator', 'Y Combinator'), ('lever', 'Lever'), ('himalayas', 'Himalayas'), ('remotive', 'Remotive'), ('weworkremotely', 'We Work Remotely'), ('jobicy', 'Jobicy'), ('mustakbil', 'Mustakbil'), ('jobspy_linkedin', 'JobSpy LinkedIn'), ('jobspy_indeed', 'JobSpy Indeed')], max_length=30),
        ),
    ]
