# Generated by Django 5.2.16 on 2026-07-30 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_search_indexes'),
        ('jobs', '0006_alter_job_source'),
    ]

    operations = [
    ]
