# Generated by Django 5.2.16 on 2026-07-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_merge_0002_job_search_indexes_0006_alter_job_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_uid', models.CharField(db_index=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
            ],
            options={
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['supabase_uid', '-saved_at'], name='jobs_savedj_supabas_4e746a_idx')],
                'unique_together': {('supabase_uid', 'job')},
            },
        ),
    ]
