# Generated by Django 5.2.16 on 2026-07-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_formatted',
            field=models.TextField(blank=True),
        ),
    ]
