# Generated by Django 5.2.16 on 2026-08-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_description_formatted'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['date_fetched'], name='jobs_job_date_fe_aec79b_idx'),
        ),
    ]
