# Generated by Django 5.2.16 on 2026-07-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('skills', models.TextField(blank=True, default='', help_text='Comma-separated list of skills, e.g. "Python, React, AWS"')),
                ('experience_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='mid', max_length=20)),
                ('preferred_roles', models.TextField(blank=True, default='', help_text='Comma-separated, e.g. "AI Engineer, ML Engineer"')),
                ('target_countries', models.TextField(blank=True, default='', help_text='Comma-separated, e.g. "Germany, United Kingdom, Remote"')),
                ('job_types_wanted', models.TextField(blank=True, default='', help_text='Comma-separated, e.g. "full-time, remote"')),
                ('min_salary', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='My CV', max_length=200)),
                ('file_path', models.FileField(upload_to='cvs/')),
                ('extracted_skills', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='profiles.profile')),
            ],
            options={
                'db_table': 'cvs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
