# Generated by Django on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='supabase_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
