# Generated by Django 5.2.16 on 2026-07-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_supabase_uid_to_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={},
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='file_path',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cv',
            name='extracted_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_types_wanted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_roles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target_countries',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='cv',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
